# _config.yml

title: ACR2025                      
url: "https://clearlab-sustech.github.io/ACR2025/"
baseurl: "/ACR2025"                      

lang: en                             
author:
  name: ClearLab SUSTECH             
  url: https://github.com/clearlab-sustech 

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme